name: "CI :: Default"

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: "**"

jobs:
  build:
    if: github.repository == 'kiegroup/kogito-editors-java' || github.event_name != 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Upload kie-wb-common-dmn-webapp-kogito-runtime
        uses: actions/upload-artifact@v2
        with:
          name: kie-wb-common-dmn-webapp-kogito-runtime
          path: "kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/target/kie-wb-common-dmn-webapp-kogito-runtime.war"

      - name: Upload kie-wb-common-stunner-bpmn-kogito-runtime
        uses: actions/upload-artifact@v2
        with:
          name: kie-wb-common-stunner-bpmn-kogito-runtime
          path: "kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/target/kie-wb-common-stunner-bpmn-kogito-runtime.war"

      - name: Upload drools-wb-scenario-simulation-editor-kogito-runtime.war
        uses: actions/upload-artifact@v2
        with:
          name: drools-wb-scenario-simulation-editor-kogito-runtime
          path: "drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/target/drools-wb-scenario-simulation-editor-kogito-runtime.war"