name: "Re-trigger Workflows on open PRs"

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  retrigger-workflows-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: tiagobento/retrigger-workflows-on-open-prs@master
        with:
          github_token: ${{ secrets.KOGITO_TOOLING_BOT_TOKEN }}
